// src/components/MindMapCard.vue
<template>
  <div class="card box-content bg-base-100 shadow">
    <figure class="w-full aspect-video">
      <MindElixirVue
        :data="map.content"
        :options="options"
        :initScale="0.2"
        class="h-full w-full"
      />
    </figure>
    <div class="m-4">
      <div class="flex items-center">
        <h2 class="font-bold overflow-hidden whitespace-nowrap text-ellipsis">
          {{ map.name }}
        </h2>
        <span v-if="map.public" class="badge ml-1">Public</span>
      </div>
      <p>{{ timeFormatter(map.updatedAt || map.date) }}</p>
    </div>
    <div class="dropdown dropdown-end absolute right-2 top-2">
      <EllipsisButton @click.prevent />
      <ul
        tabindex="0"
        class="dropdown-content z-[1] menu p-2 shadow rounded-box w-52"
        @click.prevent
      >
        <li v-if="type === 'private'" @click="emit('makePublic')">
          <a>{{ map.public ? 'Make it private' : 'Make it public' }}</a>
        </li>
        <li v-if="map.public" @click="emit('share')"><a>Share</a></li>
        <li>
          <a>Download</a>
          <ul>
            <li @click="emit('download', 'html')"><a>HTML</a></li>
            <li @click="emit('download', 'xmind')"><a>Xmind</a></li>
            <li @click="emit('download', 'json')"><a>JSON</a></li>
          </ul>
        </li>
        <li v-if="type === 'private'" @click="emit('delete')">
          <a class="hover:bg-red-500 hover:text-white">Delete</a>
        </li>
      </ul>
    </div>
  </div>
</template>
<script setup lang="ts">
import MindElixirVue from '@/components/MindElixirVue.vue'
import EllipsisButton from '@/components/EllipsisButton.vue'
import { Options } from 'mind-elixir'
import { MindMapItem } from '@/models/list'
import { timeFormatter } from '@/utils'

defineProps<{
  map: MindMapItem
  type: 'public' | 'private'
}>()

const emit = defineEmits<{
  (e: 'delete'): void
  (e: 'download', type: string): void
  (e: 'makePublic'): void
  (e: 'share'): void
}>()

const options: Partial<Options> = {
  direction: 2,
  draggable: false,
  editable: false,
  contextMenu: false,
  toolBar: false,
  keypress: false,
  overflowHidden: true,
}
</script>

// src/components/MindMapCard.tsx
'use client'

import { useState } from 'react'
import dynamic from 'next/dynamic'
import { MindMapItem } from '@/models/list'
import { Options } from 'mind-elixir'
import { MoreVertical, Download } from 'lucide-react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
} from '@/components/ui/dropdown-menu'
import { cn } from '@/lib/utils'

const MindElixirReact = dynamic(() => import('./MindElixirReact'), {
  ssr: false,
  loading: () => <div className="h-full w-full bg-muted animate-pulse rounded"></div>
})

interface MindMapCardProps {
  map: MindMapItem
  type: 'public' | 'private'
  className?: string
  onDelete: () => void
  onDownload: (type: string) => void
  onMakePublic: () => void
  onShare: () => void
}

export default function MindMapCard({
  map,
  type,
  className,
  onDelete,
  onDownload,
  onMakePublic,
  onShare,
}: MindMapCardProps) {
  const [showDropdown, setShowDropdown] = useState(false)

  const options: Partial<Options> = {
    direction: 2,
    draggable: false,
    editable: false,
    contextMenu: false,
    toolBar: false,
    keypress: false,
  }

  const timeFormatter = (dateString: string) => {
    return new Date(dateString).toLocaleDateString()
  }

  return (
    <Card className={cn("group hover:shadow-lg transition-all duration-300 overflow-hidden", className)}>
      <div className="relative w-full aspect-video bg-gradient-to-br from-blue-50 to-indigo-50 overflow-hidden">
        <div className="h-full w-full overflow-hidden pointer-events-none">
          <MindElixirReact
            data={map.content}
            options={options}
            initScale={0.2}
            className="h-full w-full"
          />
        </div>
        <div className="absolute inset-0 bg-gradient-to-t from-black/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>

        <div className="absolute right-3 top-3 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="secondary"
                size="icon"
                className="h-8 w-8 bg-background/80 backdrop-blur-sm hover:bg-background border shadow-sm"
                onClick={(e) => {
                  e.preventDefault()
                  e.stopPropagation()
                }}
              >
                <MoreVertical className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-52">
              {type === 'private' && (
                <DropdownMenuItem onClick={(e) => {
                  e.stopPropagation()
                  onMakePublic()
                }}>
                  {map.public ? 'Make Private' : 'Make Public'}
                </DropdownMenuItem>
              )}
              <DropdownMenuItem onClick={(e) => {
                e.stopPropagation()
                onShare()
              }}>
                Share
              </DropdownMenuItem>
              <DropdownMenuSub>
                <DropdownMenuSubTrigger>
                  <Download className="mr-2 h-4 w-4" />
                  Download
                </DropdownMenuSubTrigger>
                <DropdownMenuSubContent>
                  <DropdownMenuItem onClick={(e) => {
                    e.stopPropagation()
                    onDownload('json')
                  }}>
                    JSON
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={(e) => {
                    e.stopPropagation()
                    onDownload('html')
                  }}>
                    HTML
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={(e) => {
                    e.stopPropagation()
                    onDownload('xmind')
                  }}>
                    XMind
                  </DropdownMenuItem>
                </DropdownMenuSubContent>
              </DropdownMenuSub>
              {type === 'private' && (
                <DropdownMenuItem onClick={(e) => {
                  e.stopPropagation()
                  onDelete()
                }} className="text-destructive">
                  Delete
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>

      <CardContent className="p-4">
        <div className="flex items-center justify-between mb-2">
          <CardTitle className="text-base font-semibold overflow-hidden whitespace-nowrap text-ellipsis flex-1 group-hover:text-primary transition-colors duration-200">
            {map.name}
          </CardTitle>
          {map.public && (
            <Badge variant="secondary" className="ml-2">
              Public
            </Badge>
          )}
        </div>
        <p className="text-sm text-muted-foreground">{timeFormatter(map.updatedAt || map.date)}</p>
      </CardContent>
    </Card>
  )
}
